name = "Wynnic Enchantments"
author = "Rafii2198"
version = "0.17.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb36849211d8043dd1c49ca67220d1df9ca502be8574caf32fdbba1ed750ac12"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
