name = "Wynnic Enchantments"
author = "Rafii2198"
version = "0.17.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "908952bf4226a974f1e8ee11837b0f97f5a62df134e22c3591c0406997ab6871"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
