border-color=-1
caption-color=-14791145
hide-window-border=true
system-backdrop-type=DWMSBT_AUTO
text-color=-1
use-default-border-color=false
use-default-caption-color=true
use-default-text-color=true
use-immersive-dark-mode=true
window-corner-preference=DWMWCP_DEFAULT
